// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.github.zhangchengji.flying.common;

public final class CommonProto {
  private CommonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_Responses_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_Responses_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_Meta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_Meta_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014common.proto\022\006common\032\031google/protobuf/" +
      "any.proto\"s\n\007Request\022#\n\005query\030e \001(\0132\024.go" +
      "ogle.protobuf.Any\022\014\n\004page\030f \001(\005\022\020\n\010pageS" +
      "ize\030g \001(\005\022\020\n\010orderKey\030h \001(\t\022\021\n\torderDesc" +
      "\030i \001(\t\"m\n\010Response\022\r\n\004code\030\311\001 \001(\005\022\020\n\007mes" +
      "sage\030\312\001 \001(\t\022#\n\004data\030\313\001 \001(\0132\024.google.prot" +
      "obuf.Any\022\033\n\004meta\030\314\001 \001(\0132\014.common.Meta\"n\n" +
      "\tResponses\022\r\n\004code\030\311\001 \001(\005\022\020\n\007message\030\312\001 " +
      "\001(\t\022#\n\004data\030\313\001 \003(\0132\024.google.protobuf.Any" +
      "\022\033\n\004meta\030\314\001 \001(\0132\014.common.Meta\"\025\n\004Meta\022\r\n" +
      "\005total\030e \001(\003B<\n$com.github.zhangchengji." +
      "proto.commonB\013CommonProtoP\001\242\002\004HLWSb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_common_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_Request_descriptor,
        new String[] { "Query", "Page", "PageSize", "OrderKey", "OrderDesc", });
    internal_static_common_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_common_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_Response_descriptor,
        new String[] { "Code", "Message", "Data", "Meta", });
    internal_static_common_Responses_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_common_Responses_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_Responses_descriptor,
        new String[] { "Code", "Message", "Data", "Meta", });
    internal_static_common_Meta_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_common_Meta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_Meta_descriptor,
        new String[] { "Total", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
