// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.github.zhangchengji.flying.common;

public interface MetaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.Meta)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 total = 101;</code>
   * @return The total.
   */
  long getTotal();
}
