// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.github.zhangchengji.flying.common;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Any query = 101;</code>
   * @return Whether the query field is set.
   */
  boolean hasQuery();
  /**
   * <code>.google.protobuf.Any query = 101;</code>
   * @return The query.
   */
  com.google.protobuf.Any getQuery();
  /**
   * <code>.google.protobuf.Any query = 101;</code>
   */
  com.google.protobuf.AnyOrBuilder getQueryOrBuilder();

  /**
   * <code>int32 page = 102;</code>
   * @return The page.
   */
  int getPage();

  /**
   * <code>int32 pageSize = 103;</code>
   * @return The pageSize.
   */
  int getPageSize();

  /**
   * <code>string orderKey = 104;</code>
   * @return The orderKey.
   */
  String getOrderKey();
  /**
   * <code>string orderKey = 104;</code>
   * @return The bytes for orderKey.
   */
  com.google.protobuf.ByteString
      getOrderKeyBytes();

  /**
   * <code>string orderDesc = 105;</code>
   * @return The orderDesc.
   */
  String getOrderDesc();
  /**
   * <code>string orderDesc = 105;</code>
   * @return The bytes for orderDesc.
   */
  com.google.protobuf.ByteString
      getOrderDescBytes();
}
