// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.github.zhangchengji.flying.common;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 201;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string message = 202;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 202;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.google.protobuf.Any data = 203;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.google.protobuf.Any data = 203;</code>
   * @return The data.
   */
  com.google.protobuf.Any getData();
  /**
   * <code>.google.protobuf.Any data = 203;</code>
   */
  com.google.protobuf.AnyOrBuilder getDataOrBuilder();

  /**
   * <code>.common.Meta meta = 204;</code>
   * @return Whether the meta field is set.
   */
  boolean hasMeta();
  /**
   * <code>.common.Meta meta = 204;</code>
   * @return The meta.
   */
  Meta getMeta();
  /**
   * <code>.common.Meta meta = 204;</code>
   */
  MetaOrBuilder getMetaOrBuilder();
}
