// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: namespace_model.proto

package namespace

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Symbols defined in public import of google/protobuf/timestamp.proto.

type Timestamp = timestamppb.Timestamp

type Namespace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"appId" gorm:"default:appId;comment:appId;size:60;"
	AppId string `protobuf:"bytes,100,opt,name=appId,proto3" json:"appId,omitempty"`
	// @inject_tag: json:"createTime" gorm:"default:创建时间;comment:创建时间;"
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,101,opt,name=createTime,proto3" json:"createTime,omitempty"`
	// @inject_tag: json:"format" gorm:"default:格式;comment:格式;size:60;"
	Format string `protobuf:"bytes,102,opt,name=format,proto3" json:"format,omitempty"`
	// @inject_tag: json:"id" gorm:"primary_key;AUTO_INCREMENT;default:id;comment:id;size:20;"
	Id int64 `protobuf:"varint,103,opt,name=id,proto3" json:"id,omitempty"`
	// @inject_tag: json:"name" gorm:"default:命名空间名称;comment:命名空间名称;size:255;"
	Name string `protobuf:"bytes,104,opt,name=name,proto3" json:"name,omitempty"`
	// @inject_tag: json:"nodeId" gorm:"default:环境ID;comment:环境ID;"
	NodeId string `protobuf:"bytes,105,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	// @inject_tag: json:"releaseTime" gorm:"default:发布时间;comment:发布时间;"
	ReleaseTime *timestamppb.Timestamp `protobuf:"bytes,106,opt,name=releaseTime,proto3" json:"releaseTime,omitempty"`
	// @inject_tag: json:"status" gorm:"default:发布状态;comment:发布状态;"
	Status bool `protobuf:"varint,107,opt,name=status,proto3" json:"status,omitempty"`
	// @inject_tag: json:"updateTime" gorm:"default:更新时间;comment:更新时间;"
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,108,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	// @inject_tag: json:"value" gorm:"default:配置信息;comment:配置信息;size:4294967295;"
	Value string `protobuf:"bytes,109,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_namespace_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_namespace_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_namespace_model_proto_rawDescGZIP(), []int{0}
}

func (x *Namespace) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Namespace) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Namespace) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Namespace) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Namespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Namespace) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Namespace) GetReleaseTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ReleaseTime
	}
	return nil
}

func (x *Namespace) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *Namespace) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Namespace) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_namespace_model_proto protoreflect.FileDescriptor

var file_namespace_model_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xd9, 0x02, 0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x3a, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x66, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x67, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x68, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x69, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x6a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x6b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3a, 0x0a,
	0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x6c, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x6d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42,
	0x0d, 0x5a, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x00,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_namespace_model_proto_rawDescOnce sync.Once
	file_namespace_model_proto_rawDescData = file_namespace_model_proto_rawDesc
)

func file_namespace_model_proto_rawDescGZIP() []byte {
	file_namespace_model_proto_rawDescOnce.Do(func() {
		file_namespace_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_namespace_model_proto_rawDescData)
	})
	return file_namespace_model_proto_rawDescData
}

var file_namespace_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_namespace_model_proto_goTypes = []interface{}{
	(*Namespace)(nil),             // 0: namespace.Namespace
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_namespace_model_proto_depIdxs = []int32{
	1, // 0: namespace.Namespace.createTime:type_name -> google.protobuf.Timestamp
	1, // 1: namespace.Namespace.releaseTime:type_name -> google.protobuf.Timestamp
	1, // 2: namespace.Namespace.updateTime:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_namespace_model_proto_init() }
func file_namespace_model_proto_init() {
	if File_namespace_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_namespace_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Namespace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_namespace_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_namespace_model_proto_goTypes,
		DependencyIndexes: file_namespace_model_proto_depIdxs,
		MessageInfos:      file_namespace_model_proto_msgTypes,
	}.Build()
	File_namespace_model_proto = out.File
	file_namespace_model_proto_rawDesc = nil
	file_namespace_model_proto_goTypes = nil
	file_namespace_model_proto_depIdxs = nil
}
