// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_service.proto

package com.github.zhangchengji.flying.client;

public final class ClientServiceProto {
  private ClientServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024client_service.proto\022\006client\032\022client_m" +
      "odel.proto\032\014common.proto\032\033google/protobu" +
      "f/empty.proto\032\034google/api/annotations.pr" +
      "oto2\217\002\n\rClientService\0226\n\004Ping\022\026.google.p" +
      "rotobuf.Empty\032\026.google.protobuf.Empty\0224\n" +
      "\010queryApp\022\026.google.protobuf.Empty\032\020.comm" +
      "on.Response\022E\n\006config\022\016.client.Client\032\020." +
      "common.Response\"\031\202\323\344\223\002\023\"\016/client/config:" +
      "\001*\022I\n\010listener\022\016.client.Client\032\020.common." +
      "Response\"\033\202\323\344\223\002\025\"\020/client/listener:\001*BC\n" +
      "$com.github.zhangchengji.proto.clientB\022C" +
      "lientServiceProtoP\001\242\002\004HLWSb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ClientProto.getDescriptor(),
          com.github.zhangchengji.proto.common.CommonProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    ClientProto.getDescriptor();
    com.github.zhangchengji.proto.common.CommonProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
