// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_model.proto

package com.github.zhangchengji.flying.client;

public interface ClientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client.Client)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string AppId = 100;</code>
   * @return The appId.
   */
  String getAppId();
  /**
   * <code>string AppId = 100;</code>
   * @return The bytes for appId.
   */
  com.google.protobuf.ByteString
      getAppIdBytes();

  /**
   * <code>string Namespace = 101;</code>
   * @return The namespace.
   */
  String getNamespace();
  /**
   * <code>string Namespace = 101;</code>
   * @return The bytes for namespace.
   */
  com.google.protobuf.ByteString
      getNamespaceBytes();
}
