// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_model.proto

package com.github.zhangchengji.flying.client;

public final class ClientProto {
  private ClientProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_client_Client_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_client_Client_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_client_FlyingConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_client_FlyingConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022client_model.proto\022\006client\"*\n\006Client\022\r" +
      "\n\005AppId\030d \001(\t\022\021\n\tNamespace\030e \001(\t\"g\n\014Flyi" +
      "ngConfig\022\r\n\005AppId\030d \001(\t\022\025\n\rNamespaceName" +
      "\030e \001(\t\022\022\n\nReleaseKey\030f \001(\t\022\016\n\006Format\030g \001" +
      "(\t\022\r\n\005Value\030h \001(\tB<\n$com.github.zhangche" +
      "ngji.proto.clientB\013ClientProtoP\001\242\002\004HLWSb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_client_Client_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_client_Client_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_client_Client_descriptor,
        new String[] { "AppId", "Namespace", });
    internal_static_client_FlyingConfig_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_client_FlyingConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_client_FlyingConfig_descriptor,
        new String[] { "AppId", "NamespaceName", "ReleaseKey", "Format", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
