// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_model.proto

package com.github.zhangchengji.flying.client;

/**
 * Protobuf type {@code client.FlyingConfig}
 */
public final class FlyingConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:client.FlyingConfig)
        FlyingConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FlyingConfig.newBuilder() to construct.
  private FlyingConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FlyingConfig() {
    appId_ = "";
    namespaceName_ = "";
    releaseKey_ = "";
    format_ = "";
    value_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new FlyingConfig();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FlyingConfig(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 802: {
            String s = input.readStringRequireUtf8();

            appId_ = s;
            break;
          }
          case 810: {
            String s = input.readStringRequireUtf8();

            namespaceName_ = s;
            break;
          }
          case 818: {
            String s = input.readStringRequireUtf8();

            releaseKey_ = s;
            break;
          }
          case 826: {
            String s = input.readStringRequireUtf8();

            format_ = s;
            break;
          }
          case 834: {
            String s = input.readStringRequireUtf8();

            value_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ClientProto.internal_static_client_FlyingConfig_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ClientProto.internal_static_client_FlyingConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            FlyingConfig.class, FlyingConfig.Builder.class);
  }

  public static final int APPID_FIELD_NUMBER = 100;
  private volatile Object appId_;
  /**
   * <code>string AppId = 100;</code>
   * @return The appId.
   */
  @Override
  public String getAppId() {
    Object ref = appId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      appId_ = s;
      return s;
    }
  }
  /**
   * <code>string AppId = 100;</code>
   * @return The bytes for appId.
   */
  @Override
  public com.google.protobuf.ByteString
      getAppIdBytes() {
    Object ref = appId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      appId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAMESPACENAME_FIELD_NUMBER = 101;
  private volatile Object namespaceName_;
  /**
   * <code>string NamespaceName = 101;</code>
   * @return The namespaceName.
   */
  @Override
  public String getNamespaceName() {
    Object ref = namespaceName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      namespaceName_ = s;
      return s;
    }
  }
  /**
   * <code>string NamespaceName = 101;</code>
   * @return The bytes for namespaceName.
   */
  @Override
  public com.google.protobuf.ByteString
      getNamespaceNameBytes() {
    Object ref = namespaceName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      namespaceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RELEASEKEY_FIELD_NUMBER = 102;
  private volatile Object releaseKey_;
  /**
   * <code>string ReleaseKey = 102;</code>
   * @return The releaseKey.
   */
  @Override
  public String getReleaseKey() {
    Object ref = releaseKey_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      releaseKey_ = s;
      return s;
    }
  }
  /**
   * <code>string ReleaseKey = 102;</code>
   * @return The bytes for releaseKey.
   */
  @Override
  public com.google.protobuf.ByteString
      getReleaseKeyBytes() {
    Object ref = releaseKey_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      releaseKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FORMAT_FIELD_NUMBER = 103;
  private volatile Object format_;
  /**
   * <code>string Format = 103;</code>
   * @return The format.
   */
  @Override
  public String getFormat() {
    Object ref = format_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      format_ = s;
      return s;
    }
  }
  /**
   * <code>string Format = 103;</code>
   * @return The bytes for format.
   */
  @Override
  public com.google.protobuf.ByteString
      getFormatBytes() {
    Object ref = format_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      format_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUE_FIELD_NUMBER = 104;
  private volatile Object value_;
  /**
   * <code>string Value = 104;</code>
   * @return The value.
   */
  @Override
  public String getValue() {
    Object ref = value_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      value_ = s;
      return s;
    }
  }
  /**
   * <code>string Value = 104;</code>
   * @return The bytes for value.
   */
  @Override
  public com.google.protobuf.ByteString
      getValueBytes() {
    Object ref = value_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      value_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAppIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 100, appId_);
    }
    if (!getNamespaceNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 101, namespaceName_);
    }
    if (!getReleaseKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 102, releaseKey_);
    }
    if (!getFormatBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 103, format_);
    }
    if (!getValueBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 104, value_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAppIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(100, appId_);
    }
    if (!getNamespaceNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(101, namespaceName_);
    }
    if (!getReleaseKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(102, releaseKey_);
    }
    if (!getFormatBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(103, format_);
    }
    if (!getValueBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(104, value_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof FlyingConfig)) {
      return super.equals(obj);
    }
    FlyingConfig other = (FlyingConfig) obj;

    if (!getAppId()
        .equals(other.getAppId())) return false;
    if (!getNamespaceName()
        .equals(other.getNamespaceName())) return false;
    if (!getReleaseKey()
        .equals(other.getReleaseKey())) return false;
    if (!getFormat()
        .equals(other.getFormat())) return false;
    if (!getValue()
        .equals(other.getValue())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + APPID_FIELD_NUMBER;
    hash = (53 * hash) + getAppId().hashCode();
    hash = (37 * hash) + NAMESPACENAME_FIELD_NUMBER;
    hash = (53 * hash) + getNamespaceName().hashCode();
    hash = (37 * hash) + RELEASEKEY_FIELD_NUMBER;
    hash = (53 * hash) + getReleaseKey().hashCode();
    hash = (37 * hash) + FORMAT_FIELD_NUMBER;
    hash = (53 * hash) + getFormat().hashCode();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static FlyingConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FlyingConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FlyingConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FlyingConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FlyingConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FlyingConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FlyingConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FlyingConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static FlyingConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static FlyingConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static FlyingConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FlyingConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(FlyingConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code client.FlyingConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:client.FlyingConfig)
          FlyingConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ClientProto.internal_static_client_FlyingConfig_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ClientProto.internal_static_client_FlyingConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FlyingConfig.class, FlyingConfig.Builder.class);
    }

    // Construct using com.github.zhangchengji.proto.client.FlyingConfig.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      appId_ = "";

      namespaceName_ = "";

      releaseKey_ = "";

      format_ = "";

      value_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ClientProto.internal_static_client_FlyingConfig_descriptor;
    }

    @Override
    public FlyingConfig getDefaultInstanceForType() {
      return FlyingConfig.getDefaultInstance();
    }

    @Override
    public FlyingConfig build() {
      FlyingConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public FlyingConfig buildPartial() {
      FlyingConfig result = new FlyingConfig(this);
      result.appId_ = appId_;
      result.namespaceName_ = namespaceName_;
      result.releaseKey_ = releaseKey_;
      result.format_ = format_;
      result.value_ = value_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof FlyingConfig) {
        return mergeFrom((FlyingConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(FlyingConfig other) {
      if (other == FlyingConfig.getDefaultInstance()) return this;
      if (!other.getAppId().isEmpty()) {
        appId_ = other.appId_;
        onChanged();
      }
      if (!other.getNamespaceName().isEmpty()) {
        namespaceName_ = other.namespaceName_;
        onChanged();
      }
      if (!other.getReleaseKey().isEmpty()) {
        releaseKey_ = other.releaseKey_;
        onChanged();
      }
      if (!other.getFormat().isEmpty()) {
        format_ = other.format_;
        onChanged();
      }
      if (!other.getValue().isEmpty()) {
        value_ = other.value_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      FlyingConfig parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (FlyingConfig) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object appId_ = "";
    /**
     * <code>string AppId = 100;</code>
     * @return The appId.
     */
    public String getAppId() {
      Object ref = appId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        appId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string AppId = 100;</code>
     * @return The bytes for appId.
     */
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      Object ref = appId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string AppId = 100;</code>
     * @param value The appId to set.
     * @return This builder for chaining.
     */
    public Builder setAppId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      appId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string AppId = 100;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppId() {

      appId_ = getDefaultInstance().getAppId();
      onChanged();
      return this;
    }
    /**
     * <code>string AppId = 100;</code>
     * @param value The bytes for appId to set.
     * @return This builder for chaining.
     */
    public Builder setAppIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      appId_ = value;
      onChanged();
      return this;
    }

    private Object namespaceName_ = "";
    /**
     * <code>string NamespaceName = 101;</code>
     * @return The namespaceName.
     */
    public String getNamespaceName() {
      Object ref = namespaceName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        namespaceName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string NamespaceName = 101;</code>
     * @return The bytes for namespaceName.
     */
    public com.google.protobuf.ByteString
        getNamespaceNameBytes() {
      Object ref = namespaceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        namespaceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string NamespaceName = 101;</code>
     * @param value The namespaceName to set.
     * @return This builder for chaining.
     */
    public Builder setNamespaceName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      namespaceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string NamespaceName = 101;</code>
     * @return This builder for chaining.
     */
    public Builder clearNamespaceName() {

      namespaceName_ = getDefaultInstance().getNamespaceName();
      onChanged();
      return this;
    }
    /**
     * <code>string NamespaceName = 101;</code>
     * @param value The bytes for namespaceName to set.
     * @return This builder for chaining.
     */
    public Builder setNamespaceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      namespaceName_ = value;
      onChanged();
      return this;
    }

    private Object releaseKey_ = "";
    /**
     * <code>string ReleaseKey = 102;</code>
     * @return The releaseKey.
     */
    public String getReleaseKey() {
      Object ref = releaseKey_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        releaseKey_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string ReleaseKey = 102;</code>
     * @return The bytes for releaseKey.
     */
    public com.google.protobuf.ByteString
        getReleaseKeyBytes() {
      Object ref = releaseKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        releaseKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ReleaseKey = 102;</code>
     * @param value The releaseKey to set.
     * @return This builder for chaining.
     */
    public Builder setReleaseKey(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      releaseKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ReleaseKey = 102;</code>
     * @return This builder for chaining.
     */
    public Builder clearReleaseKey() {

      releaseKey_ = getDefaultInstance().getReleaseKey();
      onChanged();
      return this;
    }
    /**
     * <code>string ReleaseKey = 102;</code>
     * @param value The bytes for releaseKey to set.
     * @return This builder for chaining.
     */
    public Builder setReleaseKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      releaseKey_ = value;
      onChanged();
      return this;
    }

    private Object format_ = "";
    /**
     * <code>string Format = 103;</code>
     * @return The format.
     */
    public String getFormat() {
      Object ref = format_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        format_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string Format = 103;</code>
     * @return The bytes for format.
     */
    public com.google.protobuf.ByteString
        getFormatBytes() {
      Object ref = format_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        format_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Format = 103;</code>
     * @param value The format to set.
     * @return This builder for chaining.
     */
    public Builder setFormat(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      format_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Format = 103;</code>
     * @return This builder for chaining.
     */
    public Builder clearFormat() {

      format_ = getDefaultInstance().getFormat();
      onChanged();
      return this;
    }
    /**
     * <code>string Format = 103;</code>
     * @param value The bytes for format to set.
     * @return This builder for chaining.
     */
    public Builder setFormatBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      format_ = value;
      onChanged();
      return this;
    }

    private Object value_ = "";
    /**
     * <code>string Value = 104;</code>
     * @return The value.
     */
    public String getValue() {
      Object ref = value_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        value_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string Value = 104;</code>
     * @return The bytes for value.
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Value = 104;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Value = 104;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {

      value_ = getDefaultInstance().getValue();
      onChanged();
      return this;
    }
    /**
     * <code>string Value = 104;</code>
     * @param value The bytes for value to set.
     * @return This builder for chaining.
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      value_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:client.FlyingConfig)
  }

  // @@protoc_insertion_point(class_scope:client.FlyingConfig)
  private static final FlyingConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new FlyingConfig();
  }

  public static FlyingConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FlyingConfig>
      PARSER = new com.google.protobuf.AbstractParser<FlyingConfig>() {
    @Override
    public FlyingConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FlyingConfig(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FlyingConfig> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<FlyingConfig> getParserForType() {
    return PARSER;
  }

  @Override
  public FlyingConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

