// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_model.proto

package com.github.zhangchengji.flying.client;

public interface FlyingConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client.FlyingConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string AppId = 100;</code>
   * @return The appId.
   */
  String getAppId();
  /**
   * <code>string AppId = 100;</code>
   * @return The bytes for appId.
   */
  com.google.protobuf.ByteString
      getAppIdBytes();

  /**
   * <code>string NamespaceName = 101;</code>
   * @return The namespaceName.
   */
  String getNamespaceName();
  /**
   * <code>string NamespaceName = 101;</code>
   * @return The bytes for namespaceName.
   */
  com.google.protobuf.ByteString
      getNamespaceNameBytes();

  /**
   * <code>string ReleaseKey = 102;</code>
   * @return The releaseKey.
   */
  String getReleaseKey();
  /**
   * <code>string ReleaseKey = 102;</code>
   * @return The bytes for releaseKey.
   */
  com.google.protobuf.ByteString
      getReleaseKeyBytes();

  /**
   * <code>string Format = 103;</code>
   * @return The format.
   */
  String getFormat();
  /**
   * <code>string Format = 103;</code>
   * @return The bytes for format.
   */
  com.google.protobuf.ByteString
      getFormatBytes();

  /**
   * <code>string Value = 104;</code>
   * @return The value.
   */
  String getValue();
  /**
   * <code>string Value = 104;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
