name: Go Release

on: [push]

jobs:

  release:
    name: Build with go ${{ matrix.go_version }} on ${{ matrix.os }} and upload
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go_version: [1.14]
        os: [ubuntu-latest]

    steps:
      - name: Build
        run: cd flying-admin && go build .
      - name: Test With Coverage
        run: cd flying-admin &&  go test -v  -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
      - name: Run Vet & Lint
        run: |
          cd flying-admin &&
          go vet .
          golint -set_exit_status=1 .
