on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'

      - name: Install dependencies
        run: |
          cd flying-admin
          go version
          go get -u golang.org/x/lint/golint
      - name: Build
        run: |
          cd flying-admin
          go build .

      - name: Test With Coverage
        run: |
          cd flying-admin
          go test -gcflags=-l -v  -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Run Vet & Lint
        run: |
          cd flying-admin
          go vet ./...
          golint -set_exit_status=1 ./...